services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - transcendence-net

  backend:
    container_name: backend
    build:
      context: backend
    restart: always
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
      - ./sqlite_data:/home/node/app/sqlite_data
    ports:
      - "8000:8000"
    networks:
      - transcendence-net
    environment:
      - NODE_ENV=production
      - PORT=8000
    image: backend
    env_file:
      - .env
  
  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_REGION=us
      - NGROK_PORT=backend:8000
    networks:
      - transcendence-net

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge
