services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - transcendence-net

  backend:
    container_name: backend
    build:
      context: backend
    restart: always
    volumes:
      - /home/node/app/node_modules  # Solo para evitar sobrescritura
      - sqlite_data:/home/node/app/sqlite_data  # Volumen nombrado
    ports:
      - "8000:8000"
    networks:
      - transcendence-net
    environment:
      - NODE_ENV=production
      - PORT=8000

networks:
  transcendence-net:
    driver: bridge

volumes:
  sqlite_data:  # Volumen persistente para SQLite