services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence-net

  frontend:
    build:
      context: frontend
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - transcendence-net

  backend:
    container_name: backend
    build:
      context: backend
    restart: always
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules  # Solo para evitar sobrescritura
      - sqlite_data:/home/node/app/sqlite_data 
    expose:
      - "8000"
    networks:
      - transcendence-net
    environment:
      - NODE_ENV=production
      - PORT=8000

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    restart: always
    depends_on:
      - backend
    environment:
      - NGROK_AUTHTOKEN
      - NGROK_PORT=backend:8000
      - NGROK_REGION=es
    ports:
      - "4040:4040"  # API locale de ngrok
    networks:
      - transcendence-net

networks:
  transcendence-net:
    driver: bridge

volumes:
  sqlite_data:  # Volumen persistente para SQLite
